name: Build and Deploy Code

on: [pull_request, push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to marius
        run: echo "hello marius"